apiVersion: v1
data:
  WebHookSecretKey: <your-base64-encoded-string-from-production-pipeline-webhook-secret>
kind: Secret
metadata:
  annotations:
    jenkins.openshift.io/secret.name: production-pipeline-webhook-secret-key
  labels:
    credential.sync.jenkins.openshift.io: "true"
  name: production-pipeline-webhook-secret-key
type: Opaque