apiVersion: v1
kind: BuildConfig
metadata:
 name: production-pipeline
spec:
 runPolicy: Parallel
 source:
   git:
     ref: master
     uri: https://github.com/raksit31667/openshift-docker-image-promotion
   sourceSecret:
     name: github
   contextDir: /production
   type: Git
 strategy:
  type: JenkinsPipeline
  jenkinsPipelineStrategy:
    jenkinsfilePath: Jenkinsfile
    env:
    - name: IMAGE_NAME
    - name: NON_PROD_REGISTRY
    - name: PROD_REGISTRY
    - name: NON_PROD_PROJECT_NAME
    - name: PROD_PROJECT_NAME
    - name: GIT_COMMIT
triggers:
  - generic:
      secretReference:
        name: "production-pipeline-webhook-secret-key"
      allowEnv: true
    type: Generic