apiVersion: v1
kind: BuildConfig
metadata:
 name: production-pipeline
spec:
 runPolicy: Parallel
 source:
   git:
     ref: master
     uri: https://github.com/raksit31667/openshift-docker-image-promotion
   sourceSecret:
     name: github
   contextDir: /production
   type: Git
 strategy:
   jenkinsPipelineStrategy:
     jenkinsfilePath: Jenkinsfile
   type: JenkinsPipeline